# Generated by Django 5.2.7 on 2025-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('_value', models.BinaryField(db_column='value')),
            ],
        ),
    ]
