# Generated by Django 4.2.28 on 2026-03-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0002_country_region_city_location_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='adminparcing.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
