# Generated by Django 5.2.7 on 2025-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0002_settingapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpattern',
            name='pattern',
            field=models.JSONField(),
        ),
    ]
