# Generated by Django 5.2.7 on 2025-12-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0003_alter_textpattern_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textpattern',
            old_name='pattern',
            new_name='patterns',
        ),
    ]
