# Generated by Django 5.2.7 on 2025-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0004_rename_pattern_textpattern_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('text_patterns', models.JSONField(blank=True, default=list)),
                ('emoji_patterns', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EmojiGroup',
        ),
        migrations.DeleteModel(
            name='TextPattern',
        ),
    ]
