# Generated by Django 5.2.7 on 2025-12-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0005_alertcategory_delete_emojigroup_delete_textpattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertcategory',
            name='priority',
        ),
    ]
