# Generated by Django 5.2.7 on 2025-12-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0006_remove_alertcategory_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_end', to='adminparcing.location')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_start', to='adminparcing.location')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminparcing.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='adminparcing.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
