# Generated by Django 4.2.28 on 2026-05-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0010_city_boundary_region_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='region',
            name='boundary',
        ),
    ]
