# Generated by Django 4.2.28 on 2026-05-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_helperpresence_and_more'),
        ('adminparcing', '0011_remove_city_boundary_remove_region_boundary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertcategory',
            options={'ordering': ['category__event_class__sort_order', 'category__sort_order', 'category__name']},
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='confirm_threshold',
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='deny_threshold',
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='ttl_minutes',
        ),
        migrations.AddField(
            model_name='alertcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsing_rules', to='events.eventclassitem'),
        ),
    ]
