# Generated by Django 4.2.28 on 2026-05-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_helperpresence_and_more'),
        ('adminparcing', '0012_alter_alertcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_messages', to='events.eventclassitem')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_messages', to='adminparcing.chat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF to_regclass('public.events_parsedmessage') IS NOT NULL THEN
                    INSERT INTO adminparcing_parsedmessage (
                        id,
                        telegram_message_id,
                        author_id,
                        author_name,
                        text,
                        created_at,
                        parsed_at,
                        category_id,
                        chat_id
                    )
                    SELECT
                        id,
                        telegram_message_id,
                        author_id,
                        author_name,
                        text,
                        created_at,
                        parsed_at,
                        category_id,
                        chat_id
                    FROM events_parsedmessage
                    ON CONFLICT (id) DO NOTHING;

                    PERFORM setval(
                        pg_get_serial_sequence('adminparcing_parsedmessage', 'id'),
                        COALESCE((SELECT MAX(id) FROM adminparcing_parsedmessage), 1),
                        (SELECT COUNT(*) > 0 FROM adminparcing_parsedmessage)
                    );
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
