# Generated by Django 4.2.28 on 2026-05-23 15:29

from django.db import migrations, models


DROP_CATEGORY_FK_SQL = """
DO $$
DECLARE
    constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        WHERE nsp.nspname = 'public'
          AND rel.relname IN ('adminparcing_alertcategory', 'adminparcing_parsedmessage')
          AND con.contype = 'f'
          AND pg_get_constraintdef(con.oid) LIKE '%events_eventclassitem%'
    LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', (
            SELECT relname
            FROM pg_class
            WHERE oid = (
                SELECT conrelid
                FROM pg_constraint
                WHERE conname = constraint_name
                LIMIT 1
            )
        ), constraint_name);
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS adminparcing_alertcategory_category_id_idx
    ON adminparcing_alertcategory (category_id);
CREATE INDEX IF NOT EXISTS adminparcing_parsedmessage_category_id_idx
    ON adminparcing_parsedmessage (category_id);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("adminparcing", "0013_parsedmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertcategory",
            options={"ordering": ["class_name", "category_name", "id"]},
        ),
        migrations.AddField(
            model_name="alertcategory",
            name="category_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="alertcategory",
            name="class_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="parsedmessage",
            name="category_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE adminparcing_alertcategory ac
            SET
                category_name = COALESCE(eci.name, ''),
                class_name = COALESCE(ec.name, '')
            FROM events_eventclassitem eci
            LEFT JOIN events_eventclass ec ON ec.id = eci.event_class_id
            WHERE ac.category_id = eci.id;

            UPDATE adminparcing_parsedmessage pm
            SET category_name = COALESCE(eci.name, '')
            FROM events_eventclassitem eci
            WHERE pm.category_id = eci.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=DROP_CATEGORY_FK_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="alertcategory",
                    name="category",
                ),
                migrations.RemoveField(
                    model_name="parsedmessage",
                    name="category",
                ),
                migrations.AddField(
                    model_name="alertcategory",
                    name="category_id",
                    field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name="parsedmessage",
                    name="category_id",
                    field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
    ]
