# Generated by Django 4.2.28 on 2026-05-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0014_alter_alertcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessage',
            name='parsing_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_messages', to='adminparcing.alertcategory'),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE adminparcing_parsedmessage pm
            SET parsing_category_id = ac.id
            FROM adminparcing_alertcategory ac
            WHERE pm.parsing_category_id IS NULL
              AND pm.category_id = ac.category_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
