# Generated by Django 4.2.28 on 2026-05-24 00:00

from django.db import migrations


def copy_location_chat_to_chats(apps, schema_editor):
    Location = apps.get_model("adminparcing", "Location")
    through = Location.chats.through

    rows = []
    for location in Location.objects.exclude(chat_id__isnull=True).only("id", "chat_id").iterator():
        rows.append(through(location_id=location.id, chat_id=location.chat_id))

    if rows:
        through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0015_parsedmessage_parsing_category'),
    ]

    operations = [
        migrations.RunPython(copy_location_chat_to_chats, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='location',
            name='chat',
        ),
    ]
