# Generated by Django 5.2.7 on 2025-12-14 05:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('chat_id', models.CharField(max_length=255)),
                ('chat_title', models.CharField(max_length=255)),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='events_pars_created_b16af8_idx'), models.Index(fields=['category_id'], name='events_pars_categor_54261f_idx'), models.Index(fields=['chat_id'], name='events_pars_chat_id_3ac2c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageRouteMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('route_name', models.CharField(max_length=255)),
                ('start_place_id', models.IntegerField()),
                ('start_place_name', models.CharField(max_length=255)),
                ('end_place_id', models.IntegerField()),
                ('end_place_name', models.CharField(max_length=255)),
                ('reversed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='events.parsedmessage')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('place_name', models.CharField(max_length=255)),
                ('place_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('nlp', 'NLP'), ('route', 'Route')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='events.parsedmessage')),
            ],
        ),
    ]
