# Generated by Django 4.2.28 on 2026-05-11 09:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminparcing', '0010_city_boundary_region_boundary'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='event_classes/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventClassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='event_class_items/')),
                ('source_kind', models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], db_index=True, max_length=16)),
                ('speed_limit', models.IntegerField(default=0)),
                ('dir_type', models.IntegerField(default=1)),
                ('direction', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('ttl_minutes', models.PositiveIntegerField(default=60)),
                ('text_patterns', models.JSONField(blank=True, default=list)),
                ('emoji_patterns', models.JSONField(blank=True, default=list)),
                ('supports_direction', models.BooleanField(default=True)),
                ('supports_speed_limit', models.BooleanField(default=True)),
                ('supports_distance', models.BooleanField(default=True)),
                ('supports_angle', models.BooleanField(default=True)),
                ('supports_zone_render', models.BooleanField(default=True)),
                ('details_template', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventclass')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('auto_archive_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PocketGisSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PocketGisImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='running', max_length=16)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_disabled', models.PositiveIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='events.pocketgissource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventclassitem')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_messages', to='adminparcing.chat')),
            ],
        ),
        migrations.CreateModel(
            name='MapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed_limit', models.IntegerField(default=0)),
                ('dir_type', models.IntegerField(default=1)),
                ('direction', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('source_kind', models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], db_index=True, max_length=16)),
                ('source', models.CharField(default='user', max_length=20)),
                ('source_name', models.CharField(blank=True, default='', max_length=128)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('external_idx', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('expired', 'expired')], db_index=True, default='confirmed', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('denials', models.IntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('comment', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('class_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventclassitem')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_user_id', models.CharField(db_index=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('chat_room_id', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.helprequest')),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_request', to='events.mapevent'),
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='event_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.mapevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=64)),
                ('voter_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('vote', models.SmallIntegerField(choices=[(1, 'confirm'), (-1, 'deny')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='mapevent',
            index=models.Index(fields=['source_kind', 'is_active', 'last_seen_at'], name='events_mape_source__6494bd_idx'),
        ),
        migrations.AddIndex(
            model_name='mapevent',
            index=models.Index(fields=['class_item', 'is_active'], name='events_mape_class_i_f1d822_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequestresponse',
            unique_together={('help_request', 'responder_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventclassitem',
            unique_together={('event_class', 'name')},
        ),
        migrations.AddIndex(
            model_name='entityvote',
            index=models.Index(fields=['content_type', 'object_id'], name='events_enti_content_54aa61_idx'),
        ),
        migrations.AddIndex(
            model_name='entityvote',
            index=models.Index(fields=['user_id'], name='events_enti_user_id_f0c182_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityvote',
            unique_together={('content_type', 'object_id', 'user_id')},
        ),
    ]
