# Generated by Django 4.2.28 on 2026-02-10 05:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='event_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('voter_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vote', models.SmallIntegerField(choices=[(1, 'confirm'), (-1, 'deny')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('chat_id', models.CharField(max_length=255)),
                ('chat_title', models.CharField(max_length=255)),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category_id', models.IntegerField(db_index=True)),
                ('category_code', models.CharField(max_length=50)),
                ('category_label', models.CharField(max_length=100)),
                ('extra_params', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('expired', 'expired')], default='active', max_length=16)),
                ('confidence', models.FloatField(default=0.5)),
                ('confirmations', models.IntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('user', 'user'), ('telegram', 'telegram')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.parsedmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['created_at'], name='events_pars_created_b16af8_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['category_id'], name='events_pars_categor_54261f_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['chat_id'], name='events_pars_chat_id_3ac2c3_idx'),
        ),
        migrations.AddField(
            model_name='eventvote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.roadevent'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.roadevent'),
        ),
        migrations.AlterUniqueTogether(
            name='eventvote',
            unique_together={('event', 'user_id')},
        ),
    ]
