# Generated by Django 5.2.7 on 2025-12-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parsedmessage',
            name='events_pars_categor_54261f_idx',
        ),
        migrations.RemoveField(
            model_name='parsedmessage',
            name='category_id',
        ),
    ]
