# Generated by Django 4.2.28 on 2026-05-16 07:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='help_chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user_id', models.CharField(db_index=True, max_length=64)),
                ('helper_user_id', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_user_id', models.CharField(db_index=True, max_length=64)),
                ('solved', models.BooleanField(default=True)),
                ('rating_delta', models.SmallIntegerField(default=0)),
                ('rating_comment', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_by_user_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='creator_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='search_radius_m',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='selected_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_requests', to='events.helprequestresponse'),
        ),
        migrations.AddField(
            model_name='helprequestresponse',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequestresponse',
            name='eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequestresponse',
            name='helper_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequestresponse',
            name='helper_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('in_progress', 'in_progress'), ('waiting_confirmation', 'waiting_confirmation'), ('completed', 'completed'), ('canceled', 'canceled'), ('expired', 'expired')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='helprequestresponse',
            index=models.Index(fields=['help_request', 'accepted', 'created_at'], name='events_help_help_re_f007fa_idx'),
        ),
        migrations.AddField(
            model_name='helprequestresolution',
            name='help_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='events.helprequest'),
        ),
        migrations.AddField(
            model_name='helprequestchatroom',
            name='help_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='events.helprequest'),
        ),
        migrations.AddField(
            model_name='helprequestchatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.helprequestchatroom'),
        ),
        migrations.AddField(
            model_name='helprequestcandidate',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='events.helprequest'),
        ),
        migrations.AddIndex(
            model_name='helperpresence',
            index=models.Index(fields=['is_available', 'last_seen_at'], name='events_help_is_avai_b246fd_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestchatroom',
            index=models.Index(fields=['creator_user_id', 'helper_user_id', 'is_active'], name='events_help_creator_c87060_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestchatmessage',
            index=models.Index(fields=['room', 'created_at'], name='events_help_room_id_7a6fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestchatmessage',
            index=models.Index(fields=['sender_user_id', 'created_at'], name='events_help_sender__0039c2_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestcandidate',
            index=models.Index(fields=['help_request', 'distance_m'], name='events_help_help_re_4075cf_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestcandidate',
            index=models.Index(fields=['user_id', 'notified_at'], name='events_help_user_id_74103d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequestcandidate',
            unique_together={('help_request', 'user_id')},
        ),
    ]
