# Generated by Django 4.2.28 on 2026-03-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0003_alter_region_unique_together_location_chat_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parsedmessage',
            name='events_pars_categor_54261f_idx',
        ),
        migrations.RemoveIndex(
            model_name='parsedmessage',
            name='events_pars_chat_id_3ac2c3_idx',
        ),
        migrations.RemoveField(
            model_name='parsedmessage',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='parsedmessage',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='parsedmessage',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='parsedmessage',
            name='chat_title',
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_messages', to='adminparcing.alertcategory'),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='parsed_messages', to='adminparcing.chat'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['category'], name='events_pars_categor_54261f_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['chat'], name='events_pars_chat_id_3ac2c3_idx'),
        ),
    ]
