# Generated by Django 5.2.7 on 2025-12-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_parsedmessage_events_pars_categor_54261f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessage',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['category_id'], name='events_pars_categor_54261f_idx'),
        ),
    ]
