# Generated by Django 4.2.28 on 2026-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_helperpresence_helprequestcandidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapevent',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('expired', 'expired'), ('archived', 'archived')], db_index=True, default='confirmed', max_length=16),
        ),
    ]
