# Generated by Django 4.2.28 on 2026-04-26 07:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminparcing', '0009_location_created_at'),
        ('events', '0002_remove_parsedmessage_events_pars_categor_54261f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketGisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PocketGisSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('update_interval_hours', models.PositiveIntegerField(default=24)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('etag', models.CharField(blank=True, default='', max_length=256)),
                ('last_modified', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PocketGisImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_date', models.CharField(blank=True, default='', max_length=128)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='running', max_length=16)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_disabled', models.PositiveIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='events.pocketgissource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PocketGisPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_idx', models.IntegerField(db_index=True)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type_code', models.IntegerField(db_index=True)),
                ('speed_limit', models.IntegerField(default=0)),
                ('dir_type', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('angle', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='events.pocketgiscategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocketgis_points', to='adminparcing.city')),
                ('last_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='events.pocketgisimport')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocketgis_points', to='adminparcing.region')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='events.pocketgissource')),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'city', 'category', 'is_active'], name='events_pock_region__d4cc22_idx'), models.Index(fields=['type_code'], name='events_pock_type_co_497fa9_idx'), models.Index(fields=['source_object_id'], name='events_pock_source__e51c98_idx')],
                'unique_together': {('source', 'external_idx')},
            },
        ),
    ]
