# Generated by Django 4.2.28 on 2026-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_pocketgiscategory_pocketgissource_pocketgisimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketgiscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='pocketgis_categories/'),
        ),
        migrations.AlterField(
            model_name='pocketgiscategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
