# Generated by Django 4.2.28 on 2026-05-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_mapevent_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DROP TABLE IF EXISTS events_helprequestcandidate CASCADE;
                    DROP TABLE IF EXISTS events_helprequestchatmessage CASCADE;
                    DROP TABLE IF EXISTS events_helprequestchatroom CASCADE;
                    DROP TABLE IF EXISTS events_helprequestresolution CASCADE;
                    DROP TABLE IF EXISTS events_helprequestresponse CASCADE;
                    DROP TABLE IF EXISTS events_helperpresence CASCADE;
                    DROP TABLE IF EXISTS events_helprequest CASCADE;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='HelperPresence'),
                migrations.DeleteModel(name='HelpRequestCandidate'),
                migrations.DeleteModel(name='HelpRequestChatMessage'),
                migrations.DeleteModel(name='HelpRequestChatRoom'),
                migrations.DeleteModel(name='HelpRequestResolution'),
                migrations.DeleteModel(name='HelpRequestResponse'),
                migrations.DeleteModel(name='HelpRequest'),
            ],
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='details_template',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='dir_type',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='emoji_patterns',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='speed_limit',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='supports_angle',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='supports_direction',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='supports_distance',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='supports_speed_limit',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='supports_zone_render',
        ),
        migrations.RemoveField(
            model_name='eventclassitem',
            name='text_patterns',
        ),
        migrations.RemoveField(
            model_name='mapevent',
            name='comment',
        ),
    ]
