# Generated by Django 4.2.28 on 2026-05-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_helperpresence_and_more'),
        ('adminparcing', '0013_parsedmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsedMessage',
        ),
    ]
