# Generated by Django 4.2.28 on 2026-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_pocketgiscategory_icon_alter_pocketgiscategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketgiscategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pocketgiscategory',
            name='type_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='pocketgiscategory',
            unique_together={('type_code', 'name')},
        ),
    ]
