# Generated by Django 4.2.28 on 2026-05-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('event_created', 'event_created'), ('event_confirmed', 'event_confirmed'), ('event_denied', 'event_denied'), ('edit_approved', 'edit_approved'), ('edit_rejected', 'edit_rejected'), ('help_completed', 'help_completed'), ('help_failed', 'help_failed'), ('help_canceled', 'help_canceled')], db_index=True, max_length=64)),
                ('reputation_delta', models.IntegerField()),
                ('total_reputation', models.IntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to='accounts.identityuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
