# Generated by Django 4.2.28 on 2026-05-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reputationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('appstore', 'appstore')], default='appstore', max_length=32)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('product_id', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=16)),
                ('grants_full_access', models.BooleanField(db_index=True, default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_purchases', to='accounts.identityuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
        migrations.AddIndex(
            model_name='apppurchase',
            index=models.Index(fields=['user', 'grants_full_access'], name='accounts_ap_user_id_b60b1b_idx'),
        ),
    ]
