version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  events:
    build:
      context: ..
      dockerfile: docker/events/Dockerfile
    env_file: ../.env
    restart: always
    depends_on:
      - postgres

  adminparcing:
    build:
      context: ..
      dockerfile: docker/adminparcing/Dockerfile
    env_file: ../.env
    restart: always
    depends_on:
      - postgres
      - events

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - adminparcing
      - events

volumes:
  postgres_data: