# Generated by Django 4.2.28 on 2026-05-23 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('creator_user_id', models.CharField(db_index=True, max_length=64)),
                ('creator_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('search_radius_m', models.PositiveIntegerField(default=3000)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'active'), ('in_progress', 'in_progress'), ('waiting_confirmation', 'waiting_confirmation'), ('completed', 'completed'), ('canceled', 'canceled'), ('expired', 'expired')], db_index=True, default='active', max_length=20)),
                ('auto_archive_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_user_id', models.CharField(db_index=True, max_length=64)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('helper_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('helper_completed_at', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('chat_room_id', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assistance.helprequest')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_user_id', models.CharField(db_index=True, max_length=64)),
                ('solved', models.BooleanField(default=True)),
                ('rating_delta', models.SmallIntegerField(default=0)),
                ('rating_comment', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_by_user_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='assistance.helprequest')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user_id', models.CharField(db_index=True, max_length=64)),
                ('helper_user_id', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('help_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='assistance.helprequest')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_user_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='help_chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistance.helprequestchatroom')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='assistance.helprequest')),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='selected_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_requests', to='assistance.helprequestresponse'),
        ),
        migrations.CreateModel(
            name='HelperPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_available', 'last_seen_at'], name='assistance__is_avai_99855f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='helprequestresponse',
            index=models.Index(fields=['help_request', 'accepted', 'created_at'], name='assistance__help_re_72736f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequestresponse',
            unique_together={('help_request', 'responder_user_id')},
        ),
        migrations.AddIndex(
            model_name='helprequestchatroom',
            index=models.Index(fields=['creator_user_id', 'helper_user_id', 'is_active'], name='assistance__creator_0560e2_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestchatmessage',
            index=models.Index(fields=['room', 'created_at'], name='assistance__room_id_e0b5db_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestchatmessage',
            index=models.Index(fields=['sender_user_id', 'created_at'], name='assistance__sender__97fb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestcandidate',
            index=models.Index(fields=['help_request', 'distance_m'], name='assistance__help_re_3662c2_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequestcandidate',
            index=models.Index(fields=['user_id', 'notified_at'], name='assistance__user_id_b18b8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequestcandidate',
            unique_together={('help_request', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'created_at'], name='assistance__status_32c7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['creator_user_id', 'status'], name='assistance__creator_1d3e34_idx'),
        ),
    ]
