# Generated by Django 4.2.28 on 2026-05-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('event', 'event'), ('user', 'user')], db_index=True, max_length=16)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_review', 'in_review'), ('resolved', 'resolved'), ('rejected', 'rejected')], db_index=True, default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], db_index=True, default='medium', max_length=16)),
                ('assigned_moderator_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('opened_by_user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('sanction_type', models.CharField(choices=[('warn', 'warn'), ('restrict', 'restrict'), ('ban', 'ban')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked'), ('expired', 'expired')], db_index=True, default='active', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_user_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirm', 'confirm'), ('reject', 'reject'), ('hide', 'hide'), ('restore', 'restore'), ('warn', 'warn'), ('restrict', 'restrict'), ('ban', 'ban')], db_index=True, max_length=16)),
                ('moderator_user_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['target_type', 'target_id', 'status'], name='moderation__target__59af3c_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='moderation__status_c5a537_idx'),
        ),
    ]
