# Generated by Django 4.2.28 on 2026-05-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationcase',
            name='target_type',
            field=models.CharField(choices=[('event', 'event'), ('event_edit', 'event_edit'), ('user', 'user')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='EventEditProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.PositiveIntegerField(db_index=True)),
                ('proposer_user_id', models.CharField(db_index=True, max_length=64)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('applied', 'applied'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_edit_proposal', to='moderation.moderationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
