# Generated by Django 4.2.28 on 2026-05-24 01:48

from django.db import migrations, models
import django.db.models.deletion


def link_existing_deliveries_to_devices(apps, schema_editor):
    NotificationDelivery = apps.get_model("notifications", "NotificationDelivery")
    DeviceToken = apps.get_model("notifications", "DeviceToken")

    token_to_device_id = dict(DeviceToken.objects.values_list("token", "id"))
    deliveries = NotificationDelivery.objects.filter(device__isnull=True).exclude(token="")
    for delivery in deliveries.iterator():
        device_id = token_to_device_id.get(delivery.token)
        if device_id:
            delivery.device_id = device_id
            delivery.save(update_fields=["device"])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.devicetoken'),
        ),
        migrations.RunPython(link_existing_deliveries_to_devices, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['device', 'status'], name='notificatio_device__34a74b_idx'),
        ),
    ]
